spring.application.name=JWTToken

#spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
#
#spring.datasource.username=spicyfood
#spring.datasource.password=spicyfood
#
#spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# =========================
# JPA / HIBERNATE
# =========================

#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true
#
#spring.jpa.properties.hibernate.format_sql=true
#
#spring.jpa.database-platform=org.hibernate.dialect.OracleDialect


#spring.datasource.url=jdbc:postgresql://ep-restless-sun-ap57w008-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
#
#spring.datasource.username=neondb_owner
#
#spring.datasource.password=npg_zCWsa9kJpBq3
#
#spring.datasource.driver-class-name=org.postgresql.Driver
#
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#
#spring.jpa.hibernate.ddl-auto=update
#
#spring.jpa.show-sql=true


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.security.oauth2.client.registration.github.scope=user:email




spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
